name: Deploy to VM 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.VM_HOST }}

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Define the application directory
            APP_DIR="/home/${{ secrets.USERNAME }}/simple-api"

            # Debug: Check if APP_DIR is correctly defined
            echo "App Directory: $APP_DIR"

            # Create the directory if it doesn't exist
            mkdir -p "$APP_DIR"

            # Navigate to the application directory
            cd "$APP_DIR"

            # If there’s an existing instance, stop it
            pkill -f "node index.js" || true

            # Pull the latest code
            git init
            git remote add origin git@github.com:YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git
            git pull origin master

            # Install dependencies
            npm install

            # Start the application in the background
            nohup npm start &

            # Verify if the app is running on port 80
            lsof -i:80

      - name: Notify on Success
        if: success()
        run: echo "Deployment completed successfully!"

      - name: Notify on Failure
        if: failure()
        run: echo "Deployment failed. Please check the logs."
