name: Deploy API on Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update package index and install prerequisites
            sudo apt-get update
            sudo apt-get install -y curl rsync
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2

            # Accept the host key
            ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

            # Stop and delete all existing pm2 processes
            pm2 stop all || true
            pm2 delete all || true

            # Create the application directory on the VM
            ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "mkdir -p ~/simple-api"

            # Sync the application files from GitHub Actions runner to the VM
            rsync -avz --delete ./ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/simple-api/

            # Navigate to the application directory and install dependencies
            ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cd ~/simple-api && npm install"

            # Start the application with pm2
            ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "cd ~/simple-api && pm2 start index.js --name 'simple-api' --watch"
